name: Coq Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'
    paths:
      - '.github/workflows/coq-tests.yml'
      - 'tox.ini'
      - 'python/coqtop.py'
      - 'python/xmlInterface.py'
      - 'tests/test_coqtop.py'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  coq-tests:
    name: Coq integration tests
    # Allow installing Python 3.6 (actions/setup-python#544).
    runs-on: ubuntu-20.04
    # runs-on: ubuntu-latest
    strategy:
      matrix:
        coq_version:
          - '8.4'
          - '8.5'
          - '8.6'
          - '8.7'
          - '8.8'
          - '8.9'
          - '8.10'
          - '8.11'
          - '8.12'
          - '8.13'
          - '8.14'
          - '8.15'
          - '8.16'
          - '8.17'
          - '8.18'
          - '8.19'
          - 'master'
        py_version: ['3.6']
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
      - name: Install Cachix
        uses: cachix/cachix-action@v14
        with:
          name: coq
          skipPush: true
      - name: Set up Nix cache
        # Only Coq master needs additional caching.
        if: ${{ matrix.coq_version == 'master' }}
        uses: DeterminateSystems/magic-nix-cache-action@v2
      - name: Install Coq ${{ matrix.coq_version }}
        run: nix-env -j auto --cores 0 -i -f ci/coq.nix --argstr version ${{ matrix.coq_version }}
      - name: Install Python ${{ matrix.py_version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py_version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: Run Coq tests
        run: |
          coqtop --version
          python --version
          tox -e coq-py36
