name: Python Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'
    paths:
      - '.github/workflows/python-tests.yml'
      - 'tox.ini'
      - '**.py'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  py-tests:
    name: Python unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        py_version: ['3.6']
    steps:
      - uses: actions/checkout@v3
      - name: Install Python ${{ matrix.py_version }}
        # Allow installing Python 3.6.
        uses: MatteoH2O1999/setup-python@v1
        # uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.py_version }}
          allow-build: info
          cache-build: true
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: Run Python tests
        run: |
          python --version
          tox -e unit-py36
