name: Python Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'
    paths:
      - '.github/workflows/python-tests.yml'
      - 'tox.ini'
      - '**.py'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  py-tests:
    name: Python unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # See the comment in coq-tests.yml for why this is 3.10 instead of 3.6.
        py_version: ['3.10']
    steps:
      - uses: actions/checkout@v4
      - name: Install Python ${{ matrix.py_version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py_version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: Run Python tests
        run: |
          python --version
          tox -e unit-py310
